# Generated by Django 4.2.5 on 2023-10-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
