# Generated by Django 4.2.5 on 2023-09-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courses_course_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='minor_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
