# Generated by Django 4.2.5 on 2023-09-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_courses_minor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
