# Generated by Django 4.2.5 on 2023-10-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_coursesbought'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='no_of_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
