# Generated by Django 4.2.5 on 2023-10-02 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_courses_no_of_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='no_of_rating',
            new_name='no_of_stars',
        ),
    ]
