# Generated by Django 4.2.5 on 2023-10-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_courses_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
