# Generated by Django 4.2.5 on 2023-10-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_courses_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='stars',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
