# Generated by Django 4.2.5 on 2023-10-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_reviews_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='what_you_learn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
