# Generated by Django 4.2.5 on 2023-10-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_courses_what_you_learn'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
