# Generated by Django 4.2.5 on 2023-10-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_courses_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesbought',
            name='progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
