# Generated by Django 4.2.5 on 2023-10-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_courses_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesbought',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
