# Generated by Django 4.2.5 on 2023-10-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_remove_courses_video_courses_unlist_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
