# Generated by Django 4.2.5 on 2023-10-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_courses_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='video_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
