# Generated by Django 4.2.5 on 2023-10-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_courselessonprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesbought',
            name='progress',
        ),
    ]
