# Generated by Django 4.2.5 on 2023-10-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_remove_coursesbought_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesbought',
            name='progress',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
