# Generated by Django 4.2.5 on 2023-10-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_remove_courses_have_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='have_quiz',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
