# Generated by Django 4.2.5 on 2023-10-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_courses_have_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='video_ref',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
