# Generated by Django 4.2.5 on 2023-10-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_coursevideo_video_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='video_ref',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
