# Generated by Django 4.2.5 on 2023-10-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_alter_coursevideo_video_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='video_ref',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
